killall throughput*.sh
killall latency.sh
killall pdv.sh
killall frame_loss_rate.sh
killall lwaftr-tp
killall lwaftr-lat
killall lwaftr-pdv
rm nohup.out
rm ratetest.log
rm rate.csv
rm temp.out
rm temprate.csv
rm FLR.csv
rm FLRtest.log
rm pdv.csv
rm pdvtest.log
