# Interface parameters
IPv6-L-BG 2001:db8:6::2 # Tester's left side IPv6 address used only for the background traffic
IPv6-R-BG 2001:db8:7::2 # Tester's right side IPv6 address used only for the background traffic
IPv4-server 198.19.0.2  # IPv4 address of the simulated server

MAC-L-Tester b4:96:91:ba:0a:f2 # x034 bus31.0
MAC-R-Tester b4:96:91:ba:0a:f3 # x034 bus31.1
MAC-L-DUT b4:96:91:ba:0d:f0 # x033 bus31.0
MAC-R-DUT b4:96:91:ba:0d:f1 # x033 bus31.1

# Lw4o6 parameters
Num-lwB4s 3
IPv6-tunnel 2001:2::2 #AFTR IPv6 address  2001:db8:2::1 2001:db8:2::2
System-ports 0 # 1: use all port sets, 0: Do not use port sets that contain the system ports

# Parameters for RFC 4814 requirements
Fwd-sport-min 1024  # minimum value for background's source port in the forward direction
Fwd-sport-max 65535 # maximum value for background's source port in the forward direction
Fwd-dport-min 5000 # 1 # minumum value for destination port in the forward direction
Fwd-dport-max 49151 # maximum value for destination port in the forward direction
Rev-sport-min 1024  # minumum value for source port in the reverse direction
Rev-sport-max 65535 # maximum value for source port in the reverse direction
Rev-dport-min 5000 # 1 # minimum value for background's destination port in the reverse direction
Rev-dport-max 49151 # maximum value for background's destination port in the reverse direction

#Device parameters
CPU-L-Send 4 # Left Sender runs on this core
CPU-R-Recv 8 # Right Receiver runs on this core
CPU-R-Send 48 # Right Sender runs on this core
CPU-L-Recv 52 # Left Receiver runs on this core

MEM-Channels 8 # Number of Memory Channels


# Network traffic parameters
Forward 1 # left to right direction is active
Reverse 1 # right to left direction is active
Promisc 1 # no promiscuous mode for receiving
